version: '3'

services:
  www:
    image: nginx:latest
    volumes:
      - ./www:/usr/share/nginx/html:ro
    ports:
      - 8080:80

  arena:
    build:
      args:
        user: user
        group: user
        uid: 1000
        gid: 1000
      context: .
    volumes:
      - ./:/code
    command: ["bash", "arena.sh"]
